apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openhab
  name: openhab
  labels:
    app: openhab
spec:
  selector:
    matchLabels:
      app: openhab
  replicas: 1
  template:
    metadata:
      labels:
        app: openhab
    spec:
      containers:
      - name: openhab
        image: openhab/openhab
        volumeMounts:
        - name: openhab-data
          mountPath: /openhab/userdata
        - name: openhab-conf
          mountPath: /openhab/conf
      volumes:
      - name: openhab-data
        persistentVolumeClaim:
          claimName: openhab-pvc-data
      - name: openhab-conf
        persistentVolumeClaim:
          claimName: openhab-pvc-conf
