apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: openhab
  name: openhab-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: openhab
  name: openhab-pvc-conf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/