version: '3'

services:
#mqtt
    mosquitto:
        container_name: mqtt
        #hostname: mosquitto
        restart: always
        image: eclipse-mosquitto
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./mqtt/data:/mosquitto/data
            - ./mqtt/log:/mosquitto/log
        networks:
            - default

    openhab:
        container_name: openhab
        image: openhab/openhab
        restart: always
        volumes:
            - ./openhab/addons:/openhab/addons
            - ./openhab/conf:/openhab/conf
            - ./openhab/userdata:/openhab/userdata
        environment:
            OPENHAB_HTTP_PORT: "8081"
            OPENHAB_HTTPS_PORT: "8444"
            EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
        network_mode: host

networks:
    default:

