apiVersion: v1
kind: Service
metadata:
  namespace: openhab
  name: openhab-web
spec:
  type: LoadBalancer
  selector:
    app: openhab
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      name: webinterface
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: influxdb
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: logviewer
    - port: 9125
      targetPort: 9125
      name: xml-rpc
    - port: 9126
      targetPort: 9126
      protocol: TCP
      name: bin-rpc
 

