version: '3.3'
services:
    rancher:
        image: rancher/rancher:latest
        container_name: rancher
#        volumes:
#            - '/opt/rancher:/var/lib/rancher'
        ports:
            - 8088:80
            - 8448:443
        privileged: true
        restart: unless-stopped
